language: node_js
node_js:
  - "9"

addons:
  apt:
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

script:
  - cd explorerLibName && npm i && cd ..
  - npm run test
  - npm run lint
