language: node_js
node_js:
  - "9"

addons:
  chrome: stable

cache:
  directories:
    - node_modules

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - cd explorerLibName && npm i && cd ..
  - npm run test
  - npm run lint
